spring.application.name=inkbound
logging.file.path=logs/ 
logging.file.name=logs/application.log 

#Database
spring.datasource.url=jdbc:h2:mem:inkbound
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=inkb
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true